owner: nammoadidaphat2025
repo: phap-status

sites:
  - name: Tram Deno
    url: https://tram-phap.deno.dev

  - name: Tram Netlify
    url: https://phapgalaxy.netlify.app

  - name: Tram Cloudflare
    url: https://nammoadidaphat.pages.dev

  - name: Tram Firebase
    url: https://nammoadidaphat-2025.web.app

  - name: Tram GitHub
    url: https://nammoadidaphat2025.github.io/phap-data

  - name: Tram Tiiny
    url: https://tangphap.tiiny.site

  - name: Tram Backup 1
    url: https://tram-phap.deno.dev

  - name: Tram Backup 2
    url: https://tram-phap.deno.dev

status-website:
  baseUrl: /phap-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Trạng Thái Pháp
  introTitle: "**phap-status** là hệ thống theo dõi các Trạm Pháp – tự động cập nhật qua GitHub Actions."
  introMessage: Dùng GitHub để theo dõi 8 trạm pháp toàn cầu. Không cần server, hoàn toàn miễn phí. [**Xem GitHub**](https://github.com/nammoadidaphat2025/phap-status)
  navbar:
    - title: Trạng Thái
      href: /
    - title: GitHub Repo
      href: https://github.com/nammoadidaphat2025/phap-status
