owner: nammoadidaphat2025
repo: phap-status

sites:
  - name: Tram Deno
    url: https://tram-phap.deno.dev

  - name: Tram Netlify
    url: https://phapgalaxy.netlify.app

  - name: Tram Cloudflare
    url: https://nammoadidaphat.pages.dev

  - name: Tram Firebase
    url: https://nammoadidaphat-2025.web.app

  - name: Tram GitHub
    url: https://nammoadidaphat2025.github.io/phap-data

  - name: Tram Tiiny
    url: https://tangphap.tiiny.site

  - name: Tram Deno 2
    url: https://tram-phap.deno.dev # Nếu khác Deno chính, đổi tên

  - name: Tram Backup
    url: https://tram-phap.deno.dev # Có thể là site dự phòng hoặc sửa link khác

status-website:
  baseUrl: /phap-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Trạng Thái Pháp
  introTitle: "**phap-status** là hệ thống theo dõi các Trạm Pháp – dùng GitHub Actions để ping toàn cầu."
  introMessage: Tình trạng cập nhật tự động qua GitHub Pages – không cần máy chủ. [**Xem nguồn tại đây**](https://github.com/nammoadidaphat2025/phap-status)
  navbar:
    - title: Trạng Thái
      href: /
    - title: GitHub Repo
      href: https://github.com/nammoadidaphat2025/phap-status
